"""Inventory gate (PLAN §4): rows, vintage and gaps per dataset -> data/processed/INVENTORY.md.

Built from the processed tables (what the app actually uses) plus raw/pull_log.json (what each pull got).
Surprises listed here are copied verbatim into docs/LIMITATIONS.md.
"""
from __future__ import annotations

import json

import pandas as pd

from .common import PROCESSED, RAW, STORMS


def _mb(path) -> str:
    return f"{path.stat().st_size / 1e6:.2f} MB"


def main() -> None:
    log = json.loads((RAW / "pull_log.json").read_text()) if (RAW / "pull_log.json").exists() else {}
    adv = pd.read_parquet(PROCESSED / "advisories.parquet")
    cty = pd.read_parquet(PROCESSED / "advisory_county.parquet")
    out = pd.read_parquet(PROCESSED / "outages_county.parquet")
    reg = pd.read_parquet(PROCESSED / "registry.parquet")
    hwm = pd.read_parquet(PROCESSED / "hwm_ian.parquet")
    ps = pd.read_parquet(PROCESSED / "psurge_sites.parquet")
    subs = reg[reg["type"] == "substation"]
    screening = subs[subs["fema_zone"].isin(["VE", "V", "AE", "A", "AO", "AH"])]

    L = ["# Data inventory", "",
         "Generated by `src/pull/inventory.py` from `data/processed/` and `data/raw/pull_log.json`.",
         "Units: outage counts are customers (meters), not people (PRD R7). Heights are metres NAVD88 unless stated.", "",
         "## Datasets", "",
         "| ID | Dataset | Rows in use | Vintage | Source used | Gaps |", "|---|---|---|---|---|---|"]
    wsp = adv[adv["product"] == "wsp64"]
    for sid, s in STORMS.items():
        w = wsp[wsp["storm_id"] == sid]
        miss = log.get("D2", {}).get("results", {}).get(sid, {}).get("missing", [])
        L.append(f"| D2 | Wind speed prob., {s['name']} | {len(w)} advisories x 67 counties | "
                 f"{w.advisory_time.min():%Y-%m-%d %HZ} to {w.advisory_time.max():%Y-%m-%d %HZ} | NHC GIS archive, "
                 f"{', '.join(sorted(w.resolution.unique()))} | {'none' if not miss else ', '.join(miss)} |")
    d3 = log.get("D3", {})
    got = sorted(int(x) for x in ps.threshold_ft.unique())
    absent = [n for n in d3.get("thresholds_ft", got) if n not in got]
    gap = f"{absent} ft not retrieved; default offset (1.0 m) uses 3 ft" if absent else "none"
    L.append(f"| D3 | P-Surge, Ian | {ps.advisory_time.nunique()} advisories x thresholds {got} ft x "
             f"{ps.asset_id.nunique()} substations | {ps.advisory_time.min():%Y-%m-%d %HZ} to "
             f"{ps.advisory_time.max():%Y-%m-%d %HZ} | NHC GIS P-Surge archive | {gap} |")
    for sid, s in STORMS.items():
        o = out[out["storm_id"] == sid]
        L.append(f"| D7 | EAGLE-I peak outages, {s['name']} | {int(o.observed.sum())} counties | {s['year']}, 15-min | "
                 f"figshare 10.6084/m9.figshare.24237376 | {int((o.peak_out_net > o.customers).sum())} counties capped at 100% (MCC undercount) |")
    L.append(f"| D7 | Customers per county (MCC) | {out.fips.nunique()} counties | EAGLE-I release | figshare MCC.csv | "
             f"2024 `total_customers` kept for reference only |")
    for t, label in [("substation", "D4 substations (OSM)"), ("line", "D4 transmission line segments (HIFLD)"),
                     ("plant", "D5 wastewater plants (EPA FRS + OSM)"), ("pumping", "D5b pumping stations (OSM)"),
                     ("hospital", "D12 hospitals (HIFLD)")]:
        r = reg[reg["type"] == t]
        L.append(f"| {label.split()[0]} | {label.split(' ', 1)[1]} | {len(r)} in Lee + Charlotte | "
                 f"{'; '.join(sorted(r.source_vintage.dropna().unique())[:3])} | {r.source.iloc[0] if len(r) else ''} | "
                 f"{'no switchgear height, no condition attributes' if t == 'substation' else ''} |")
    L.append(f"| D6 | FEMA flood zone at asset | {int(reg.fema_zone.notna().sum())} assets | effective NFHL | "
             f"Esri Living Atlas NFHL reduced set | {int(reg.fema_zone_subtype.astype(str).str.startswith('Minimal').sum())} "
             f"assets outside reduced set, inferred Zone X |")
    L.append(f"| D8 | Ian high-water marks | {len(hwm)} in Lee + Charlotte (NAVD88) | Sept-Oct 2022 | USGS STN event 325 | "
             f"{int(hwm.height_above_gnd_m.isna().sum())} without height above ground |")
    L.append(f"| D9 | Ground elevation at asset | {int(reg.ground_elev_m.notna().sum())} of {len(reg)} | 3DEP current | "
             f"USGS EPQS | {int(reg.ground_elev_m.isna().sum())} UNKNOWN |")
    L += ["", "## Registry summary", "",
          f"- Substations: {len(subs)}; in the Decision B screening set (VE/V/AE/A/AO/AH): {len(screening)}.",
          f"- Screening-set substations with a NAVD88 BFE: {int(screening.bfe_m_navd88.notna().sum())}.",
          f"- Dependent assets with a PLACEHOLDER FEED: {int((reg.feed_kind == 'PLACEHOLDER').sum())}; "
          f"with no plausible feed (> 10 km): {int((reg.feed_kind == 'NONE').sum())}.",
          f"- Ground elevation, substations: median {subs.ground_elev_m.median():.2f} m, "
          f"range {subs.ground_elev_m.min():.2f} to {subs.ground_elev_m.max():.2f} m NAVD88.",
          "", "## Processed files", ""]
    L += [f"- `{p.name}` — {_mb(p)}" for p in sorted(PROCESSED.glob("*.parquet"))]
    total = sum(p.stat().st_size for p in PROCESSED.glob("*")) / 1e6
    L += ["", f"Total `data/processed/`: {total:.1f} MB (gate: < 50 MB).", "",
          "## Surprises (copied to docs/LIMITATIONS.md)", "",
          "1. NHC's archive has no `tenthDeg` wind-probability files for 2022-2024; the high-resolution product is `5km` "
          "(0.05 deg contour bands). All 67 advisories use 5km; probabilities are band midpoints.",
          "2. HIFLD Electric Substations is no longer published anywhere reachable, and the NASA NCCS HIFLD mirror did not "
          "respond. Substations come from OpenStreetMap (pre-authorised fallback); feeds are nearest OSM substation.",
          "3. hazards.fema.gov reset every connection. Flood zones come from Esri's Living Atlas copy of NFHL (reduced set), "
          "which omits unshaded Zone X; assets outside it are labelled 'X, inferred'.",
          "4. EAGLE-I came from the figshare release (no login), not the ORNL Globus pages. The 2024 `total_customers` field "
          "overstates several counties (Miami-Dade 1.9x the modeled count), so MCC is the denominator.",
          "5. Real P-Surge exists for Ian, so Decision B on Ian uses PSURGE probabilities, not the STATIC fallback. "
          "STATIC remains the path for any advisory without a P-Surge snapshot (e.g. Milton in this prototype).",
          "6. OSM maps only a handful of pumping (lift) stations in Lee and Charlotte; the P4 list is illustrative, not complete.",
          "7. Ian's P-Surge gave >= 0.8 probability of > 3 ft above ground at several Zone X substations. A FEMA-zone "
          "screening set (PRD C5) would not look at them.",
          "8. EAGLE-I shows Lee County at about 73% of MCC customers out at Ian's peak, below utility-reported figures; "
          "EAGLE-I coverage of a county's utilities is incomplete, so fractions are a floor."]
    (PROCESSED / "INVENTORY.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
